### ISSUE TITLE
Error node wallet.js

### ISSUE THREAD

**Issue by Beetario** [kamikazechaser/tele-bitcoin-wallet#2]
Hi, thanks for you work, is awesome
i have this error when run node wallet.js, please helpme 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (/root/GunbotTradingBot/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/root/GunbotTradingBot/wallet.js:52:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

```

**Comment by kamikazechaser** [comment]
Change the port number.
